[build]
  publish = "build/"
  command = "CI= npm run build"

[build.environment]
  NODE_VERSION = "16"
  NPM_FLAGS = "--no-audit --no-fund"

[[redirects]]
  from = "/api/*"
  to = "https://synchroai-api.herokuapp.com/api/:splat"
  status = 200
  force = true

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
